### ISSUE TITLE
(Is `THANKS!` an issue? ;-)

### ISSUE THREAD

**Issue by iDGS** [dsparks83/statamic-word-truncate#1]
[https://lodge.statamic.com/support/1967-got-a-closetags-modifier-or-equivalent#reply-19](https://lodge.statamic.com/support/1967-got-a-closetags-modifier-or-equivalent#reply-19)

**Comment by dsparks83** [comment]
Nope, I've added support to update your ending although it's probably safer to change it via directly editing the code.
